
winpty  docker run -it \
  -e PGADMIN_DEFAULT_EMAIL="admin@admin.com" \
  -e PGADMIN_DEFAULT_PASSWORD="root" \
  -p 8080:80 \
  --network=pg-network \
  --name pgadmin \
  dpage/pgadmin4




winpty docker run -it \
  -e POSTGRES_USER="root" \
  -e POSTGRES_PASSWORD="root" \
  -e POSTGRES_DB="ny_taxi" \
  -v /D:/zoom_data_engineering_bootcamp/docker_sql/my_taxi_postgres_data  \ 
  -p 5432:5432 \
  --network=pg-network-2 \
  --name pg-database \
  postgres:13
  